name: dockerhub-deployment

on:
  push:
    branches: master

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 1.8
      # enable experimental status for docker in order to support SMUI's backend tests that rely on Ryuk images
      # (see https://github.com/actions/virtual-environments/issues/368)
      - name: Docker experimental Status
        run: |
          docker version -f '{{.Server.Experimental}}'
      - name: Docker restart (with experimental status)
        run: |
          sudo rm /etc/docker/daemon.json || true
          echo $'{ "experimental": true }' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - uses: actions/checkout@v2
      - name: Setup NPM environment specfic to SMUI
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm i graceful-fs
      - run: npm i resolve
      - run: npm i esutils
      - run: npm i semver
      - name: Run tests
        run: sbt test
      # https://github.community/t/github-actions-docker-login/16053/3
      # https://community.atlassian.com/t5/Bitbucket-questions/Piplenes-docker-login-can-not-perform-an-interactive-login-from/qaq-p/595736
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#      # see https://github.com/marketplace/actions/docker-login
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & deploy SMUI
        run: |
          make docker-build-only > build.log 2>&1
          make docker-push
